Repository lucasarruda9/PyLua, pull requests merged in 2025-05, with the labels that each got.

#14 docs: adiciona documento de sprints realizadas ao projeto
  docs/Metodologia/sprints_realizadas.md
Labels: documentation

#16 fix: Corrige anormalidade da automação do template de issue
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/issue_template.yml
Labels: bug

#23 Tratamento erros
  docs/Metodologia/sprints_realizadas.md
  lexer/scanner.l
  parser/parser.y
Labels: enhancement

#30 Ast/diagrama
  docs/Diagramas/AST/assets/diagrama.png
  docs/Diagramas/AST/ast.md
Labels: documentation

#29 docs: Ajustes no cronograma das sprints
  docs/Metodologia/Sprints.md
Labels: documentation
