Repository lucasarruda9/PyLua, pull requests merged in 2025-06, with the labels that each got.

#38 Feat/indentacao
  Makefile
  compilar.sh
  docs/Metodologia/sprints_realizadas.md
  docs/testes.md
  lexer/scanner.l
  parser/parser.y
  run_tests.sh
  tests/parser/test3.txt
  verificar_deps.sh
Labels: enhancement

#45 Docs/ajuste geral documentacao
  .gitignore
  README.md
  docs/Metodologia/decisoes_tecnicas.md
  docs/Metodologia/sprints_realizadas.md
  docs/analisador_lexico.md
  docs/analisador_sintatico.md
  docs/arquitetura.md
  docs/ast_documentacao.md
  docs/gerador_codigo.md
Labels: documentation

#52 Feature/mais nos
  ast/ast.c
  ast/ast.h
  gerador_codigo_final/gerador_codigo_final.c
  lexer/scanner.l
  parser/parser.y
  tabela/tabela.c
Labels: enhancement

#50 fix: removi arquivos bash de testes e criei o pylua.sh como o principal
  compilar.sh
  inicializar_projeto.sh
  pylua.sh
  run_tests.sh
  testar_gerador.sh
  verificar_deps.sh
Labels: bug

#53 feat: Adição da estrutura inicial do código intermediário
  Makefile
  codigo_intermediario/codigo_intermediario.c
  codigo_intermediario/codigo_intermediario.h
Labels: enhancement

#57 Merge/correcoes para main
  ast/ast.c
  ast/ast.h
  codigo_intermediario/codigo_intermediario.c
  exemplos/teste_funcao.py
  exemplos/teste_if.py
  exemplos/teste_while.py
  gerador_codigo_final/gerador_codigo_final.c
  lexer/scanner.l
  parser/parser.y
Labels: enhancement

#59 adicionando codigo de conduta e pasta da semana2
  CODE_OF_CONDUCT.md
  docs/Semana 2/scanner.l
Labels: documentation

#63 Refactor/makefile e pylua.sh
  Makefile
  docs/Metodologia/decisoes_tecnicas.md
  docs/compilador/analisador_lexico.md
  docs/compilador/analisador_sintatico.md
  docs/compilador/arquitetura.md
  docs/compilador/ast_documentacao.md
  docs/compilador/gerador_codigo.md
  docs/compilador/testes.md
  docs/testes.md
  exemplos_gabaritos/teste_gerador.txt
  pylua.sh
  tests/ast/test_controle.c
  tests/ast/test_funcoes.c
  tests/ast/test_novos_nos.c
  tests/expected_outputs/test3.txt
  tests/parser/test3.txt
  tests/teste_gerador.py
Labels: documentation
